ROLE_GUIDANCE = {
    "sde": {
        "display_name": "Software Development Engineer",
        "must_have_skills": [
            "python",
            "java",
            "data structures",
            "algorithms",
            "sql",
            "git",
            "rest api",
            "testing",
        ],
        "nice_to_have_skills": [
            "django",
            "fastapi",
            "system design",
            "docker",
            "aws",
            "linux",
            "ci/cd",
        ],
        "improvement_areas": [
            "Add impact-focused bullets with measurable outcomes.",
            "Highlight backend projects with APIs, databases, and deployment.",
            "Show evidence of problem solving, ownership, and code quality.",
        ],
        "keywords": [
            "software engineer",
            "backend",
            "full stack",
            "api",
            "microservices",
            "scalability",
        ],
    },
    "data_scientist": {
        "display_name": "Data Scientist",
        "must_have_skills": [
            "python",
            "statistics",
            "machine learning",
            "sql",
            "data analysis",
            "pandas",
            "numpy",
        ],
        "nice_to_have_skills": [
            "tensorflow",
            "pytorch",
            "scikit-learn",
            "data visualization",
            "experimentation",
            "a/b testing",
        ],
        "improvement_areas": [
            "Show model-building work with metrics such as accuracy, F1, or RMSE.",
            "Include business impact, not only technical implementation.",
            "Call out datasets, experimentation process, and deployment if applicable.",
        ],
        "keywords": [
            "predictive modeling",
            "analytics",
            "feature engineering",
            "experiments",
        ],
    },
    "frontend": {
        "display_name": "Frontend Engineer",
        "must_have_skills": [
            "javascript",
            "typescript",
            "html",
            "css",
            "react",
            "git",
            "testing",
        ],
        "nice_to_have_skills": [
            "next.js",
            "accessibility",
            "performance optimization",
            "state management",
            "design systems",
        ],
        "improvement_areas": [
            "Include shipped UI features and their user or business impact.",
            "Mention responsiveness, accessibility, and performance work.",
            "Point to reusable components, design system, or testing ownership.",
        ],
        "keywords": [
            "ui",
            "ux",
            "web performance",
            "responsive design",
        ],
    },
}
