# Generated by Django 6.0.1 on 2026-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='parsed_resume',
            field=models.JSONField(blank=True, help_text='Full parsed resume payload stored for later downstream features', null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='parser_source',
            field=models.CharField(default='unknown', help_text='Indicates whether the real parser or dummy parser produced the stored result', max_length=20),
        ),
    ]
